fix(easydev): docker pull images

diff --git a/utilities/openemr-cmd/openemr-cmd b/utilities/openemr-cmd/openemr-cmd
--- a/utilities/openemr-cmd/openemr-cmd
+++ b/utilities/openemr-cmd/openemr-cmd
@@ -9,14 +9,16 @@ set -euo pipefail
 # Copyright : Copyright (c) 2020 Reid Liu <guliu@redhat.com>
 # Copyright : Copyright (c) 2020-2025 Brady Miller <brady.g.miller@gmail.com>
 # Copyright : Copyright (c) 2025 Matt Summers <matt@openCoreEMR.com>
+# Copyright : Copyright (c) 2026 Stephen Waite <stephen.waite@open-emr.org>
 # Author    : Reid Liu <guliu@redhat.com>
 # Author    : Brady Miller <brady.g.miller@gmail.com>
 # Author    : Matt Summers <matt@openCoreEMR.com>
+# Author    : Stephen Waite <stephen.waite@open-emr.org>
 # License   : https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
 #################################################################################################
 
 # Increment the version when modify script
-VERSION="1.0.24"
+VERSION="1.0.25"
 # If the docker is snap or non-snap docker
 # Setting the container names accordingly
 get_container_names() {
@@ -328,20 +330,42 @@ set-webroot(){
 }
 
 docker-pull-image(){
+    local host_openemr_path
+    host_openemr_path=$(docker inspect "${CONTAINER_ID}" \
+        --format '{{range .Mounts}}{{if eq .Destination "/var/www/localhost/htdocs/openemr"}}{{.Source}}{{end}}{{end}}')
+
+    if [[ -z "${host_openemr_path}" ]]; then
+        echo "Error: Could not determine host OpenEMR path from container mounts." >&2
+        exit 1
+    fi
+
+    local COMPOSE_FILE="${host_openemr_path}/docker/development-easy/docker-compose.yml"
+
+    if [[ ! -f "${COMPOSE_FILE}" ]]; then
+        echo "Error: docker-compose.yml not found at ${COMPOSE_FILE}" >&2
+        exit 1
+    fi
+
+    check_docker_compose_install
+
     local docker_images
-    docker_images=$(docker ps --format "table {{.Image}}")
+    docker_images=$("${DOCKER_COMPOSE_CMD[@]}" -f "${COMPOSE_FILE}" config --images 2>/dev/null)
+
+    if [[ -z "${docker_images}" ]]; then
+        echo "No images found in ${COMPOSE_FILE}"
+        return
+    fi
+
     local IMAGE RESP
-    for IMAGE in ${docker_images}; do
-        if [[ "${IMAGE}" != "IMAGE" ]]; then
-            # Use -r with read
-            read -r -e -p "Do you wish to pull ${IMAGE} ? (y) " RESP
-            if [[ "${RESP,,}" = y ]]; then
-                docker pull "${IMAGE}"
-            else
-                echo "Skipping ${IMAGE}"
-            fi
+    while IFS= read -r IMAGE; do
+        [[ -z "${IMAGE}" ]] && continue
+        read -r -e -p "Do you wish to pull ${IMAGE} ? [Y/n] " RESP </dev/tty
+        if [[ -z "${RESP}" || "${RESP,,}" = y ]]; then
+            docker pull "${IMAGE}"
+        else
+            echo "Skipping ${IMAGE}"
         fi
-    done
+    done <<< "${docker_images}"
 }
 
 USAGE_EXIT_CODE=13
